# Generated by Django 4.1.1 on 2024-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantOrdered',
            fields=[
                ('merchantId', models.IntegerField(primary_key=True, serialize=False)),
                ('pinCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PinOrdered',
            fields=[
                ('pinCode', models.IntegerField(primary_key=True, serialize=False)),
                ('merchantId', models.IntegerField()),
            ],
        ),
    ]
