# Generated by Django 4.1.1 on 2024-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantordered',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinordered',
            name='id',
            field=models.BigAutoField(auto_created=True, default=89349, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchantordered',
            name='merchantId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pinordered',
            name='pinCode',
            field=models.IntegerField(),
        ),
    ]
